package com.aichat.app.domain.model

enum class ProviderType(val displayName: String) {
    OPENAI("OpenAI"),
    CLAUDE("Anthropic Claude"),
    GEMINI("Google Gemini"),
    DEEPSEEK("DeepSeek"),
    OPENROUTER("OpenRouter"),
    GROQ("Groq"),
    TOGETHER("Together AI"),
    FIREWORKS("Fireworks AI"),
    CEREBRAS("Cerebras"),
    MISTRAL("Mistral AI"),
    COHERE("Cohere"),
    PERPLEXITY("Perplexity"),
    XAI("xAI (Grok)"),
    HYPERBOLIC("Hyperbolic"),
    NOVITA("Novita AI"),
    SILICONFLOW("SiliconFlow"),
    QWEN("Qwen APIs"),
    MOONSHOT("Moonshot AI"),
    SAMBANOVA("SambaNova"),
    OLLAMA("Ollama"),
    LM_STUDIO("LM Studio"),
    VLLM("vLLM"),
    LITELLM("LiteLLM"),
    OPENAI_COMPATIBLE("OpenAI-compatible"),
    CUSTOM("Custom Provider"),
}
